# Generated by Django 3.1.7 on 2021-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elec_name', models.CharField(default=' ', max_length=40)),
                ('elec_type', models.TextField(choices=[('national', 'national'), ('city', 'city')])),
                ('elec_status', models.TextField(choices=[('active', 'active'), ('pending', 'pending'), ('ended', 'ended')], default='pending')),
            ],
        ),
    ]
