# Generated by Django 3.1.7 on 2021-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(default=' ', max_length=40)),
                ('elec_name', models.CharField(default='', max_length=41)),
                ('candidate_type', models.TextField(choices=[('MP', 'MP'), ('MAYOR', 'MAYOR'), ('COUNCILLOR', 'COUNCILLOR'), ('RESREVED', 'RESREVED')])),
                ('party_name', models.TextField(choices=[('AL', 'AL'), ('BNP', 'BNP'), ('JP', 'JP'), ('COMMUNIST', 'COMMUNIST'), ('SELF PARTY', 'SELF PARTY')])),
                ('voting_area', models.CharField(db_column='Area Name', default='', max_length=10)),
                ('voting_ward', models.CharField(db_column='Ward Number', default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DummyCitizenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='default.jpg', upload_to='profile_pictures')),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('father_name', models.CharField(db_column='Father Name', max_length=30)),
                ('mother_name', models.CharField(db_column='Mother Name', max_length=30)),
                ('nid', models.CharField(default='', max_length=16)),
                ('gender', models.CharField(blank=True, default='', max_length=6)),
                ('email', models.EmailField(db_column='Email', max_length=19)),
                ('phone', models.CharField(db_column='Phone Number', max_length=11)),
                ('area_name', models.CharField(db_column='Area Name', max_length=10)),
                ('ward_number', models.CharField(db_column='Ward Number', max_length=10)),
                ('dob', models.DateField()),
                ('elec_Worker', models.BooleanField(default=False)),
            ],
        ),
    ]
