# Generated by Django 3.1.7 on 2021-05-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(default=' ', max_length=40)),
                ('elec_name', models.CharField(default='', max_length=41)),
                ('candidate_type', models.TextField(choices=[('MP', 'MP'), ('MAYOR', 'MAYOR'), ('COUNCILLOR', 'COUNCILLOR'), ('RESREVED', 'RESREVED')])),
                ('party_name', models.TextField(choices=[('AL', 'AL'), ('BNP', 'BNP'), ('JP', 'JP'), ('COMMUNIST', 'COMMUNIST'), ('SELF PARTY', 'SELF PARTY')])),
                ('voting_area', models.CharField(db_column='Area Name', default='', max_length=10)),
                ('voting_ward', models.CharField(db_column='Ward Number', default='', max_length=10)),
            ],
        ),
    ]
