# Generated by Django 3.1.7 on 2021-05-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_caninfo'),
        ('vote', '0002_auto_20210523_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateInfo',
        ),
    ]
