# Generated by Django 3.1.7 on 2021-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_candidateinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caninfo',
            name='nid',
        ),
        migrations.AddField(
            model_name='caninfo',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
