# Generated by Django 3.1.7 on 2021-05-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210523_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='caninfo',
            name='nid',
            field=models.CharField(default='', max_length=40),
        ),
    ]
