# Generated by Django 3.1.7 on 2021-05-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_caninfo_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caninfo',
            name='candidate_type',
            field=models.TextField(choices=[('MP', 'MP'), ('MAYOR', 'MAYOR'), ('COUNCILLOR', 'COUNCILLOR'), ('RESERVED', 'RESERVED')]),
        ),
    ]
